"""init schema

Revision ID: f3b7c41a1333
Revises: 
Create Date: 2026-01-12 15:51:14.243636

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b7c41a1333'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_label_owner_name')
    )
    op.create_index(op.f('ix_label_name'), 'label', ['name'], unique=False)
    op.create_index(op.f('ix_label_owner_id'), 'label', ['owner_id'], unique=False)
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_owner_id'), 'note', ['owner_id'], unique=False)
    op.create_table('label_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('READ', 'EDIT', name='sharerole'), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_id', 'user_id', name='uq_label_user')
    )
    op.create_index(op.f('ix_label_share_label_id'), 'label_share', ['label_id'], unique=False)
    op.create_index(op.f('ix_label_share_user_id'), 'label_share', ['user_id'], unique=False)
    op.create_table('note_label_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'label_id', name='uq_note_label_link')
    )
    op.create_index(op.f('ix_note_label_link_label_id'), 'note_label_link', ['label_id'], unique=False)
    op.create_index(op.f('ix_note_label_link_note_id'), 'note_label_link', ['note_id'], unique=False)
    op.create_table('note_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('READ', 'EDIT', name='sharerole'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'user_id', name='uq_note_user')
    )
    op.create_index(op.f('ix_note_share_note_id'), 'note_share', ['note_id'], unique=False)
    op.create_index(op.f('ix_note_share_user_id'), 'note_share', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_share_user_id'), table_name='note_share')
    op.drop_index(op.f('ix_note_share_note_id'), table_name='note_share')
    op.drop_table('note_share')
    op.drop_index(op.f('ix_note_label_link_note_id'), table_name='note_label_link')
    op.drop_index(op.f('ix_note_label_link_label_id'), table_name='note_label_link')
    op.drop_table('note_label_link')
    op.drop_index(op.f('ix_label_share_user_id'), table_name='label_share')
    op.drop_index(op.f('ix_label_share_label_id'), table_name='label_share')
    op.drop_table('label_share')
    op.drop_index(op.f('ix_note_owner_id'), table_name='note')
    op.drop_table('note')
    op.drop_index(op.f('ix_label_owner_id'), table_name='label')
    op.drop_index(op.f('ix_label_name'), table_name='label')
    op.drop_table('label')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
